### ISSUE TITLE
Default sort isn't the game default

### ISSUE THREAD

**Issue by JasonHorkles** [emmett-shark/SongOrganizer#3]
When the mod is installed, the "Default" sort method isn't what the game normally does, but is rather in alphabetical order

**Comment by emmett-shark** [comment]
I never noticed because they both feel giga arbitrary, but it should be fixed on next release.
https://github.com/emmett-shark/SongOrganizer/commit/f1d3ac9222f79184078dbb3232170104173fcb38#diff-df6265e0c3559a0328788203727ee9b2dde09bc914658eb75593d113c68f0fe3R33

**Comment by JasonHorkles** [comment]
Thank you!!
